### ISSUE TITLE
Proposal: File Structure

### ISSUE THREAD

**Issue by dwidjaja945** [team-hack/react-components#11]
For concise files per component, I propose a file structure of a similar sort:

- components
| -- ComponentName
| ---- ComponentName.tsx
| ---- ComponentName.scss/css
| ---- ComponentName.test.tsx
| ---- ComponentName.story.tsx
| ---- index.tsx

`index.tsx` will simply import and export the component and any exported items.
```
// index.tsx
import ComponentName from './ComponentName';

export * from './ComponentName';
export default ComponentName;
```

This file structure is followed by Dan Abromov and Material-UI

**Comment by vijayxtreme** [comment]
Love this structure.  Pinning for now, if people already are doing JS, that's fine, make it similar to this structure and at a later date we can move things to TSX for anyone who needs help.

**Comment by kamilAqil** [comment]
i have recently started using absolute imports in my projects. From my understanding this is a good approach for reusing components because imports are relative to the src of library. Anyhow i was trying to see how to configure it in storybook, and it seems some are using webpack 

module.exports = {
  //...
  resolve: {
    modules: [path.resolve(__dirname, 'src'), 'node_modules']
  }
};


does anyone have any ideas about using absolute imports in the project ? or is it already configured lol

**Comment by dwidjaja945** [comment]
If possible, I'd prefer to have alias imports, but I usually configure that in webpack, which this project doesn't seem to use.
I know `storybook` allows you to extend the webpack configuration, but I'm not sure how that affects the runtime checks for imports.

I don't think it is already configured, but I am also not too familiar with the build system of this project either.

**Comment by kamilAqil** [comment]
I think either options solves the ../ dependency hell. I also do not know the effect on run time, but that is an interesting point to look at. 

Setting up some pattern or config seems important because i feel there are a lot of moving pieces

**Comment by vijayxtreme** [comment]
Thanks for bringing this up, I think it's worth spending some time looking into a good way to get this configured.  @kamilAqil, do you think you can do some research and check in with me later (maybe Discord)  later in the week?  We can compare notes.

**Comment by vijayxtreme** [comment]
Closing -- I think we figured out file structure for now.  Check out the latest commit for this repo (at time of writing) for examples like Alert or Card
