### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by jamesnewking** [team-hack/react-components#17]
Need description and process for unit testing.

I recommend Jest

**Comment by dwidjaja945** [comment]
in tandem with jest, I'd also recommend `@testing-library/react`.

**Comment by vijayxtreme** [comment]
Jest works 👍

**Comment by vijayxtreme** [comment]
It'd be great to come up with some standard tests to check for while building a component.  Does anyone have any specific tests they like to run?  Maybe if everyone can add their thoughts, we can wrap this up into some kind of shared document to reference later in the Wiki area.

**Comment by vijayxtreme** [comment]
To test, simply just run `yarn test --watchAll` in your project, and it should pick up any files that end with extension `.test.js`.  If anyone needs help with this be sure to reach out via my calendly for paired programming: https://calendly.com/hackbuddy

**Comment by davemcg3** [comment]
I've done some reading around tests and one thing I've found is that you generally don't want to test private methods. Now, JavaScript doesn't really have those, but... the essence of that statement is that you don't want to test the internal implementation of your component. You want to test that with a certain set of inputs you get a certain output consistently. How the component internally processes the inputs to get that output doesn't really matter, but any edge of your component that is talking to a different component you should test, so if a component is called with certain props and it makes an api call and then takes the response of the api call and process that to render an output, maybe a list of something, you want to test that _an_ api call is made with the correct parameters, then mock the response of that api call and make sure the output of the component is the intended list based on the mocked response. What this allows you to do is internally refactor the component entirely and as long as you're not changing the inputs or outputs you don't need to change your tests based on the refactor.

**Comment by dwidjaja945** [comment]
From my understanding, you don't need to test implementation details. It is best to just test what the user _would_ see on the UI. So mostly the presence or absence of UI elements, UI changes per some event fire etc.

**Comment by vijayxtreme** [comment]
Closing and moving to discussions
