### ISSUE TITLE
Proposal: Include PopperJS

### ISSUE THREAD

**Issue by dwidjaja945** [team-hack/react-components#5]
Fairly early on at this point, but for many reusable components, we would likely need them to appear above DOM elements, or appear outside the normal flow of the document.

I propose we include `popper.js` as our positioning engine. This package does not have any dependencies.

Material-UI currently uses this same library under the hood.

Applicable Components:
- Modals
- Tooltips
- Menus
- Dropdown
- Callouts
- Snackbars
- Alerts

https://www.npmjs.com/package/popper.js/v/1.14.3

**Comment by vijayxtreme** [comment]
Sounds good.  Can you submit a PR?
