### ISSUE TITLE
Enterprise Style System

### ISSUE THREAD

**Issue by TheDanishDynamo** [team-hack/react-components#7]
Any recommendations on a complete enterprise design system that is more than bootstrap and material.

1) It has to be restrictive, no artistic freedom
2) It has to have components like people picker
3) It has to have CRUD and list

It could be based off e.g. Salesforce or existing enterprise app

**Comment by vijayxtreme** [comment]
If you want to make some "enterprise" style components that would be a great feature addition.  I haven't seen that in Bootstrap or Material, so could be fun for our project.  Feel free to create new issues.  However, if it's too complex for now we can circle back later.

**Comment by TheDanishDynamo** [comment]
It is more along the lines of UI patterns, which includes functionality, in addition to styling. The vision is that 90% of all UX functionality is developed using existing patterns. The patterns are demonstrated in a sample app like this ugly app https://serenity.is/demo/Account/Login/?ReturnUrl=%2Fdemo%2F. The UX manifesto/zen is ugly is better than pretty when it comes to consistency.
