### ISSUE TITLE
Standardized branch naming convention

### ISSUE THREAD

**Issue by jamesnewking** [team-hack/react-components#8]
We should have some standardized branch naming convention

for example:
[https://gist.github.com/digitaljhelms/4287848](https://gist.github.com/digitaljhelms/4287848)

Suggestions?

**Comment by vijayxtreme** [comment]
Definitely -- let's work on this a little later, as I want everyone to feel comfortable with making pull requests.   But longer term, I do want to move to a more "git flow" style branch naming convention.  If you feel like you already know what you are doing, please lead the way with your branch naming, and we will discuss at next meetup so everyone can be on the same page.
