### ISSUE TITLE
Proposal: Build library with Typescript

### ISSUE THREAD

**Issue by dwidjaja945** [team-hack/react-components#9]
Typescript will allow the library to be significantly more maintainable and easier to use for the user by providing stronger type checks.

### Effort
I'm not familiar with the current build system for this project - I'm only really familiar with `webpack` at this time.

Configure the current build system to handle ts.
Include and configure `tsconfig`.
- Would also allow us to include import alias as well

**Comment by vijayxtreme** [comment]
@dwidjaja945 Can you please configure the tsconfig and make a pull request.  That way after anyone who wants to create TS files can?  I'll merge into master.  Also tying to issue #11

**Comment by vijayxtreme** [comment]
Just checking, this is done right? Our project now supports TS? Should I close and move to Done?

**Comment by dwidjaja945** [comment]
@vijayxtreme  yeah should be good to go as far as I know.

**Comment by vijayxtreme** [comment]
Cool, closed.
